# Generated by Django 3.1.5 on 2021-01-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='parent',
        ),
        migrations.AddField(
            model_name='subgroup',
            name='slug',
            field=models.SlugField(default='subgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='backend.subgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='backend.thread'),
        ),
    ]
